trigger:
- master

pool:
  name: MyAgentPool

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.x'

- script: dotnet restore StringLibrary.slnx
  displayName: Restore

- script: dotnet build StringLibrary.slnx --configuration Release
  displayName: Build

- script: dotnet pack StringLibrary/StringLibrary.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: Pack NuGet

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishVstsFeed: 'string-extensions-feed'
